[package]
name = "example"
version.workspace = true
authors.workspace = true
edition.workspace = true

description = ""
repository = ""

keywords = []
categories = []

publish.workspace = true

[features]

[dependencies]

[dev-dependencies]

[build-dependencies]

[target.'cfg(loom)'.dependencies]
loom = { workspace = true }
