version = "Two"

unstable_features = true

# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true

# Macros
format_macro_matchers = true
format_macro_bodies = true

# Comments
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true

# Code
newline_style = "Unix"
match_block_trailing_comma = true
reorder_impl_items = true
